const SCROLL_DIRECTION = 'SCROLL_DIRECTION';
const SEARCH_CHAPTER_TEXT = 'SEARCH_CHAPTER_TEXT';
const IS_KEYBOARD_OPEN = 'IS_KEYBOARD_OPEN';

const reduxTypes = {
  SCROLL_DIRECTION,
  SEARCH_CHAPTER_TEXT,
  IS_KEYBOARD_OPEN,
};

export default reduxTypes;
