const SCROLL_DIRECTION = 'SCROLL_DIRECTION';
const CURRENT_REGULATION_CHAPTER = 'CURRENT_REGULATION_CHAPTER';

const reduxTypes = {
  SCROLL_DIRECTION,
  CURRENT_REGULATION_CHAPTER,
};

export default reduxTypes;
